Fixed syntax-error

diff --git a/upload-script b/upload-script
--- a/upload-script
+++ b/upload-script
@@ -11,8 +11,8 @@ fi
 
 # Ensure that there is a pattern specified.
 if [[ -z "$1" ]]; then
-  echo "Missing file (pattern) to upload."
-  exit 1
+    echo "Missing file (pattern) to upload."
+    exit 1
 fi
 
 # Only upload to non-draft releases
@@ -64,7 +64,8 @@ if [ -e .github/build ]; then
     else
         echo "*****************************************************************"
         echo " Artifacts are already present, skipping the legacy build-script."
-        echo "*****************************************************************"    fi
+        echo "*****************************************************************"
+    fi
 fi
 
 # Prepare the headers
